<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aeropuertos [ 
    <!ELEMENT aeropuertos (aeropuerto*)> 
    <!ELEMENT aeropuerto (nombre, cerrado?)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT cerrado EMPTY>
]>

<aeropuertos> 
    <aeropuerto>
        <nombre>Berlin Schonefeld (SFX)</nombre>
    </aeropuerto>
    <aeropuerto>
        <nombre>Berl√≠n Tempehof (THF)</nombre>
        <cerrado/>
    </aeropuerto>
</aeropuertos> 